# Generated by Django 4.2.28 on 2026-08-02 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Disciplina')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Turma')),
                ('periodo', models.CharField(blank=True, max_length=40, verbose_name='Período')),
                ('ano_letivo', models.CharField(blank=True, max_length=9, verbose_name='Ano letivo')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('ssh', 'SSH (terminal)'), ('samba', 'Samba (compartilhamento de arquivos)'), ('mysql', 'MySQL (database próprio)'), ('pasta', 'Pasta de arquivos (share)')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor', models.CharField(blank=True, help_text='Ex: nome do database MySQL, caminho do share, ou "shell" p/ SSH', max_length=120, verbose_name='Valor/parâmetro')),
            ],
            options={
                'ordering': ['tipo', 'nome'],
                'unique_together': {('nome', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Google')),
                ('turmas', models.ManyToManyField(blank=True, related_name='professores', to='alunos.turma')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Google (@escola.edu.br)')),
                ('ra', models.CharField(blank=True, max_length=40, unique=True, verbose_name='RA/Matrícula')),
                ('username_linux', models.CharField(blank=True, help_text='Preenchido automaticamente na criação da conta.', max_length=32, unique=True, verbose_name='Login Linux/SSH/Samba')),
                ('ativo', models.BooleanField(default=True, help_text='Desativar bloqueia SSH+Samba+MySQL na hora.', verbose_name='Acesso ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('disciplinas', models.ManyToManyField(blank=True, related_name='alunos', to='alunos.disciplina', verbose_name='Disciplinas matriculadas')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='alunos.turma')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AcessoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Autorizado')),
                ('senha_recurso', models.CharField(blank=True, max_length=128, verbose_name='Senha do recurso (ex: db MySQL)')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='alunos.aluno')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_alunos', to='alunos.recurso')),
            ],
            options={
                'ordering': ['aluno', 'recurso'],
                'unique_together': {('aluno', 'recurso')},
            },
        ),
    ]
